apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
#  username: root
#  password: password
  cursos_url: msvc_cursos:8002
---  # Separa archivos
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
#  username: postgres
#  password: password
  usuarios_url: msvc-usuarios:8001
