apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msvc-cursos # COINCIDE selecciona los pods
  template:
    metadata:
      labels:
        app: msvc-cursos # COINCIDE
    spec:
      containers:
        - image: toxxii/cursos:latest
          name: cursos
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name:  DB_HOST
              value: "postgres14:5432"
            - name: DB_DATABASE
              value: "msvc_cursos"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: USUARIOS_URL
              value: "msvc-usuarios:8001"
