apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos # COINCIDE selecciona los pods
  template:
    metadata:
      labels:
        app: msvc-cursos # COINCIDE
    spec:
      containers:
        - image: toxxii/cursos:latest
          name: cursos
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: usuarios_url
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8002
#              scheme: HTTP
#            initialDelaySeconds: 15
#            periodSeconds: 15
#            timeoutSeconds: 20
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8002
#              scheme: HTTP
#            initialDelaySeconds: 15
#            periodSeconds: 15
#            timeoutSeconds: 20
#          resources:
#            requests:
#              memory: "1024Mi" # MB de ram
#              cpu: "800m"
#            limits:
#              memory: "1400Mi"
#              cpu: "1000m"
