version: "3.9"  # Version de docker-compose, afecta a las funcionalidades
services:
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: toxxii/usuarios:latest
#    build:
#      context: ./ #La raiz, el punto de partida
#      dockerfile: ./msvc-usuarios/Dockerfile #Solo las crea si no estan creadas
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: password
      CURSOS_URL: ec2-18-208-119-225.compute-1.amazonaws.com:8002
    networks:
      spring:
    depends_on:
      - mysql8 #Primero tiene que estar levantado mysql8, despues de que se levante,levanta msvc_usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
#    external: true

networks:
  spring:
    name: spring