apiVersion: v1
kind: PersistentVolume
metadata:
  # Con esto se solicita
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
# storageClassName: standard # Proporciona informacion para la conf del persistant volume
  storageClassName: "" # Proporciona informacion para la conf del persistant volume
  accessModes:
    - ReadWriteMany  # Para poder leer entre nodos
#   - ReadWriteOnce
#  hostPath: # emptyDir: dentro del Pod // hostPath: fuera del pod
#    path: /var/lib/mysql
#    type: DirectoryOrCreate # Si no existe esta carpeta la crea
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09a6b3223db2937b0
