apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv # mismo que en mysql-pv
  accessModes:
    - ReadWriteOnce # Tiene que coincidir con alguno ed mysql-pv
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi