apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  username: cm9vdA==
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=