apiVersion: v1
kind: Service
metadata:
  name: postgres14 #se tiene que utilizar el mismo, es el nombre del host para la comunicacion interna
spec:
  ports:
    - port: 5432 # Del servicio al pod
      protocol: TCP
      targetPort: 5432 # Puerto que se aber en el contenedor
  selector:
    app: postgres # selecciona los pods
  type: ClusterIP # comunicacion interna
