apiVersion: v1
kind: Service
metadata:
  name: msvc-cursos
spec:
  ports:
    - port: 8002 # Puerto del servicio para el trafico
      protocol: TCP
      targetPort: 8002 # Puerto interno
  selector:
    app: msvc-cursos # Selecciona los pods con la etiquita template->metadata->label->app
  type: LoadBalancer # Para comunicacion interna
