apiVersion: v1
kind: Service
metadata:
  name: msvc-auth # mismo nombre que el deployment y que el nombre del application.properties
spec:
  ports:
    - port: 9000 # Puerto del servicio para el trafico
      protocol: TCP
      targetPort: 9000 # Puerto interno
  selector:
    app: msvc-auth # Selecciona los pods con la etiquita template->metadata->label->app
  type: LoadBalancer # Para comunicacion internal
