apiVersion: v1
kind: Service
metadata:
  name: msvc-usuarios
spec:
  ports:
    - port: 8001 # Puerto del servicio para el trafico
      protocol: TCP
      targetPort: 8001 # Puerto interno
  selector:
    app: msvc-usuarios # Selecciona los pods con la etiquita template->metadata->label->app
  type: LoadBalancer # Para comunicacion interna
